### ISSUE TITLE
Slice bounds out of range

### ISSUE THREAD

**Issue by oleksiiti** [futzu/cuei#5]
When parsing certain SCTE-35 cues I get a panic:
```
panic: runtime error: slice bounds out of range [:408] with length 400

goroutine 1 [running]:
github.com/futzu/cuei.(*bitDecoder).chunk(0x14000118e40, 0x8)
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/bitter.go:27 +0xac
github.com/futzu/cuei.(*bitDecoder).uInt64(0x10426bc20?, 0x14000120240?)
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/bitter.go:55 +0x1c
github.com/futzu/cuei.(*bitDecoder).uInt8(...)
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/bitter.go:34
github.com/futzu/cuei.(*Descriptor).decodeSegmentation(0x14000118d30, 0x14000118e40)
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/descriptors.go:211 +0x144
github.com/futzu/cuei.(*Descriptor).segmentationDescriptor(0x14000118d30, 0x14000118e40, 0xb8?, 0x8c?)
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/descriptors.go:165 +0x118
github.com/futzu/cuei.(*Descriptor).decode(0x0?, 0x2?, 0x0?, 0x0?)
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/descriptors.go:91 +0x8c
github.com/futzu/cuei.(*Cue).dscptrLoop(0x1400012e040, 0x19, 0x14000118e40)
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/cue.go:77 +0xc8
github.com/futzu/cuei.(*Cue).decodeBytes(0x1400012e040, {0x14000128040?, 0x14000118ea8?, 0x1?})
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/cue.go:58 +0xdc
github.com/futzu/cuei.(*Cue).Decode(0x1400012e040, {0x104266f40?, 0x14000118f18?})
        /Users/oleksiitorunov/go/pkg/mod/github.com/futzu/cuei@v1.1.89/cue.go:40 +0x104
```

The cue I'm attempting to decode: `/DA0AAAAAAAAAAAABQb/UN6ZgAAZAhdDVUVJAIdqN3/TAAApMXgICNP3GiIAAL/Pk3w=`

Decoding it like this:
```
c := cuei.NewCue()
ok := c.Decode("/DA0AAAAAAAAAAAABQb/UN6ZgAAZAhdDVUVJAIdqN3/TAAApMXgICNP3GiIAAL/Pk3w=")
if !ok {
    fmt.Println("failed to decode")
    os.Exit(1)
}
```

It's worth mentioning that I encoded this cue myself. So I believe it's the encoding that doesn't function properly. For example, if I decode a cue and then encode it again without changing any of its fields I get a somewhat different cue:
```
c := cuei.NewCue()
ok := c.Decode("/DA0AAAAAAAAAAAABQaB4zZ7tQAeAhxDVUVJAA6GjwDQAAESy7EICAAAAAAA0/cuIgAAXljZSQ==")
if !ok {
    fmt.Println("failed to decode")
    os.Exit(1)
}

fmt.Println(c.Encode2B64()) // Prints "/DA0AAAAAAAAAAAABQb/4zZ7tQAZAhdDVUVJAA6Gj3/TAAESy7EICNP3LiIAALikDmY="
```

And then it panics when I try to decode the resulting cue.

Can you take a look into it?

Thanks!

**Comment by futzu** [comment]
Update man,
There is a bug in the version you're using.
I redid the JSON stuff, it is much better. It shows all the proper values for Descriptors and Commands.

Your encoding is fine, it works with 1.1.93.

```json
{
    "InfoSection": {
        "Name": "Splice Info Section",
        "TableID": "0xfc",
        "SectionSyntaxIndicator": false,
        "Private": false,
        "SapType": 3,
        "SapDetails": "No Sap Type",
        "SectionLength": 52,
        "ProtocolVersion": 0,
        "EncryptedPacket": false,
        "EncryptionAlgorithm": 0,
        "PtsAdjustment": 0,
        "CwIndex": "0x0",
        "Tier": "0x0",
        "CommandLength": 5,
        "CommandType": 6
    },
    "Command": {
        "Name": "Time Signal",
        "CommandType": 6,
        "TimeSpecifiedFlag": true,
        "PTS": 90077.399344
    },
    "DescriptorLoopLength": 30,
    "Descriptors": [
        {
            "SegmentationEventID": "0xe868f",
            "SegmentationEventCancelIndicator": false,
            "SegmentationEventIDComplianceIndicator": false,
            "ProgramSegmentationFlag": true,
            "SegmentationDurationFlag": true,
            "DeliveryNotRestrictedFlag": false,
            "WebDeliveryAllowedFlag": true,
            "NoRegionalBlackoutFlag": false,
            "ArchiveAllowedFlag": false,
            "DeviceRestrictions": "Restrict Group 0",
            "SegmentationDuration": 200.1001,
            "SegmentationMessage": "Break Start",
            "SegmentationUpidType": 8,
            "SegmentationUpidLength": 8,
            "SegmentationUpid": {
                "Name": "AiringID",
                "UpidType": 8,
                "Value": "\ufffd\ufffd."
            },
            "SegmentationTypeID": 34,
            "SegmentNum": 0,
            "SegmentsExpected": 0,
            "SubSegmentNum": 0,
            "SubSegmentsExpected": 0
        }
    ],
    "Crc32": 1582881097
}
```

**Comment by futzu** [comment]
It looks like it's dropping the upid value on the encode for some reason. Not sure why.

**Comment by futzu** [comment]
"/DA0AAAAAAAAAAAABQaB4zZ7tQAeAhxDVUVJAA6GjwDQAAESy7EICAAAAAAA0/cuIgAAXljZSQ=="

the descriptor and upid lengths are wrong. Cuei re-calculates the lengths when it encodes. 

Your UPID length is eight bytes  but your UPID value is only three bytes long that's why it's encoding differently, the descriptor is 5 bytes shorter .

**Comment by futzu** [comment]
I just had to redo the segmentation descriptor stuff because they updated the specification and changed some stuff around. 
So it might be me,  I don't have time to go through it all right now, but if you update it will fix the error you're getting now. The re-encode stuff I will go through when I get a chance.

**Comment by futzu** [comment]
I found it. I had the wrong method in the map for UPID type 8.

```json
{
    "InfoSection": {
        "Name": "Splice Info Section",
        "TableID": "0xfc",
        "SectionSyntaxIndicator": false,
        "Private": false,
        "SapType": 3,
        "SapDetails": "No Sap Type",
        "SectionLength": 52,
        "ProtocolVersion": 0,
        "EncryptedPacket": false,
        "EncryptionAlgorithm": 0,
        "PtsAdjustment": 0,
        "CwIndex": "0x0",
        "Tier": "0x0",
        "CommandLength": 5,
        "CommandType": 6
    },
    "Command": {
        "Name": "Time Signal",
        "CommandType": 6,
        "TimeSpecifiedFlag": true,
        "PTS": 90077.399344
    },
    "DescriptorLoopLength": 30,
    "Descriptors": [
        {
            "Tag": 2,
            "Length": 28,
            "Identifier": "CUEI",
            "Name": "Segmentation Descriptor",
            "SegmentationEventID": "0xe868f",
            "SegmentationEventCancelIndicator": false,
            "SegmentationEventIDComplianceIndicator": false,
            "ProgramSegmentationFlag": true,
            "SegmentationDurationFlag": true,
            "DeliveryNotRestrictedFlag": false,
            "WebDeliveryAllowedFlag": true,
            "NoRegionalBlackoutFlag": false,
            "ArchiveAllowedFlag": false,
            "DeviceRestrictions": "Restrict Group 0",
            "SegmentationDuration": 200.1001,
            "SegmentationMessage": "Break Start",
            "SegmentationUpidType": 8,
            "SegmentationUpidLength": 8,
            "SegmentationUpid": {
                "Name": "AiringID",
                "UpidType": 8,
                "Value": "0xd3f72e"
            },
            "SegmentationTypeID": 34,
            "SegmentNum": 0,
            "SegmentsExpected": 0,
            "SubSegmentNum": 0,
            "SubSegmentsExpected": 0
        }
    ],
    "Crc32": 1582881097
```
I'll do a new release  in the morning.

**Comment by futzu** [comment]
v1.1.95 is up

https://github.com/futzu/cuei/compare/v1.1.89...v1.1.95

**Comment by futzu** [comment]
"/DA0AAAAAAAAAAAABQb/UN6ZgAAZAhdDVUVJAIdqN3/TAAApMXgICNP3GiIAAL/Pk3w=" is failing  
but just re-encode it and it should come out working 
re-encoding "/DA0AAAAAAAAAAAABQaB4zZ7tQAeAhxDVUVJAA6GjwDQAAESy7EICAAAAAAA0/cuIgAAXljZSQ=="
 produces   " /DA0AAAAAAAAAAAABQb/4zZ7tQAeAhxDVUVJAA6Gjz/TAAESy7EICAAAAAAA0/cuIgAAjFLk9Q=="

The only difference I see in the values is the CRC.

**Comment by futzu** [comment]
```go
cee := "/DA0AAAAAAAAAAAABQaB4zZ7tQAeAhxDVUVJAA6GjwDQAAESy7EICAAAAAAA0/cuIgAAXljZSQ=="

c := cuei.NewCue()
c.Decode(cee)
fmt.Println("Before ",cee)
fmt.Println("After  ",c.Encode2B64())

dee := "/DA0AAAAAAAAAAAABQb/4zZ7tQAeAhxDVUVJAA6Gjz/TAAESy7EICAAAAAAA0/cuIgAAjFLk9Q=="
d:= cuei.NewCue()
d.Decode(dee)
fmt.Println("Before ",dee)
fmt.Println("After  ", d.Encode2B64()) 
```

```bash
Before  /DA0AAAAAAAAAAAABQaB4zZ7tQAeAhxDVUVJAA6GjwDQAAESy7EICAAAAAAA0/cuIgAAXljZSQ==
After   /DA0AAAAAAAAAAAABQb/4zZ7tQAeAhxDVUVJAA6Gjz/TAAESy7EICAAAAAAA0/cuIgAAjFLk9Q==

Before  /DA0AAAAAAAAAAAABQb/4zZ7tQAeAhxDVUVJAA6Gjz/TAAESy7EICAAAAAAA0/cuIgAAjFLk9Q==
After   /DA0AAAAAAAAAAAABQb/4zZ7tQAeAhxDVUVJAA6Gjz/TAAESy7EICAAAAAAA0/cuIgAAjFLk9Q==
```
